"""user upgrade

Revision ID: 581338659d81
Revises: 58788462cc89
Create Date: 2019-02-21 11:35:44.809946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581338659d81'
down_revision = '58788462cc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
